// @ts-check

/**
 * The sidebar is hand-written rather than autogenerated so the reading order is a
 * deliberate journey: orient → build → understand → verify → ship → get help.
 *
 * This file is the single source of truth for doc order, category labels, and the
 * category index slugs. Directory names are kept short; the public slug is set here.
 */

/** A monospace section divider between sidebar groups. */
const section = (label) => ({
  type: 'html',
  value: `<div class="sidebarSection">${label}</div>`,
  defaultStyle: false,
});

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    section('Start here'),
    'index',
    'start-here/quickstart',
    'start-here/core-concepts',
    'start-here/choose-your-path',

    section('Build'),
    {
      type: 'category',
      label: 'Platform Capabilities',
      link: {
        type: 'generated-index',
        slug: '/platform-capabilities',
        title: 'Platform Capabilities',
        description:
          'What the platform actually does: the wallet as identity anchor, Litecoin blockchain-as-a-service, authentication, payments, and the MCP automation layer.',
      },
      items: [
        'platform-capabilities/pteri-wallet',
        'platform-capabilities/blockchain-as-a-service',
        'platform-capabilities/identity-and-authentication',
        'platform-capabilities/payments-and-intent-authorization',
        'platform-capabilities/intelligence-automation-and-mcp',
        'platform-capabilities/one-platform-many-use-cases',
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      link: {
        type: 'generated-index',
        slug: '/api-reference',
        title: 'API Reference',
        description:
          'How to authenticate, every operation in the published OpenAPI spec, and what to do when a call fails.',
      },
      items: [
        'api-reference/authentication',
        'api-reference/endpoints',
        'api-reference/errors',
        'api-reference/standard',
        'api-reference/enterprise',
      ],
    },
    {
      type: 'category',
      label: 'SDKs & Integration',
      link: {
        type: 'generated-index',
        slug: '/sdks-and-integration',
        title: 'SDKs & Integration',
        description:
          'Official clients for eleven languages, plus the OpenAPI spec if yours is not one of them.',
      },
      items: ['sdks/api-clients'],
    },
    {
      type: 'category',
      label: 'AI Agents & MCP',
      link: {
        type: 'generated-index',
        slug: '/ai-agents-and-mcp',
        title: 'AI Agents & MCP',
        description:
          'Why agent security is broken today, and how to give an agent cryptographic authority instead of a stored API key.',
      },
      items: [
        'ai-agents-and-mcp/why-ai-systems-are-insecure',
        'ai-agents-and-mcp/pteri-for-ai-authority',
        'ai-agents-and-mcp/pteri-intelligence-and-mcp',
      ],
    },

    section('Understand'),
    {
      type: 'category',
      label: 'Foundations',
      link: {
        type: 'generated-index',
        slug: '/foundations',
        title: 'Foundations',
        description:
          'Why shared-secret identity fails, why payments inherit that failure, and what PTERI keeps from Web3.',
      },
      items: [
        'foundations/why-identity-fails-in-web2',
        'foundations/why-payments-fail',
        'foundations/what-web3-got-right',
      ],
    },
    {
      type: 'category',
      label: 'The PTERI Model',
      link: {
        type: 'generated-index',
        slug: '/pteri-model',
        title: 'The PTERI Model',
        description:
          'Five constraints, one trust layer, and an explicit list of what PTERI deliberately is not.',
      },
      items: [
        'pteri-model/core-mental-model',
        'pteri-model/universal-trust-layer',
        'pteri-model/what-pteri-is-not',
      ],
    },
    {
      type: 'category',
      label: 'Payments & Identity',
      link: {
        type: 'generated-index',
        slug: '/payments-and-identity',
        title: 'Payments & Identity',
        description:
          'The UTXO model, identity-bound intent, optional MWEB privacy, verifiable settlement, and eSIM device migration.',
      },
      items: [
        'payments-and-identity/utxo-model',
        'payments-and-identity/identity-bound-intent',
        'payments-and-identity/mweb-privacy',
        'payments-and-identity/verifiable-settlement',
        'payments-and-identity/esim-identity',
      ],
    },
    {
      type: 'category',
      label: 'Comparisons',
      link: {
        type: 'generated-index',
        slug: '/comparisons',
        title: 'Comparisons & Obsolescence',
        description:
          'What cryptographic authority replaces: passwords, OTP, static API keys, custodians, token stacks, and policy engines.',
      },
      items: [
        'comparisons/passwords',
        'comparisons/otp-and-authenticator-apps',
        'comparisons/static-api-keys',
        'comparisons/custodial-payments',
        'comparisons/smart-contract-stacks',
        'comparisons/zero-trust-policy-systems',
      ],
    },

    section('Trust & operate'),
    {
      type: 'category',
      label: 'Architecture & Security',
      link: {
        type: 'generated-index',
        slug: '/architecture-and-security',
        title: 'Architecture & Security',
        description:
          'Where every secret lives, the canonical authentication flow, and how keys stay on the device.',
      },
      items: [
        'architecture-and-security/where-things-live',
        'architecture-and-security/authentication-flow',
        'architecture-and-security/key-custody-and-biometrics',
      ],
    },
    {
      type: 'category',
      label: 'Threat Model',
      link: {
        type: 'generated-index',
        slug: '/threat-model',
        title: 'Threat Model & Cryptography',
        description:
          'Which attack classes are structurally eliminated, which are explicitly out of scope, and the primitives underneath.',
      },
      items: [
        'threat-model/overview',
        'threat-model/threats-eliminated',
        'threat-model/out-of-scope',
        'threat-model/cryptographic-foundations',
        'threat-model/why-determinism-matters',
        'threat-model/security-as-architecture',
      ],
    },
    {
      type: 'category',
      label: 'Operations & Scaling',
      link: {
        type: 'generated-index',
        slug: '/operations-and-scaling',
        title: 'Operations & Scaling',
        description:
          'Running this in production: stateless services, horizontal scaling, failure modes, observability, and who owns what.',
      },
      items: [
        'operations/stateless-by-design',
        'operations/horizontal-scaling',
        'operations/blockchain-at-scale',
        'operations/rate-limiting',
        'operations/failure-modes',
        'operations/observability',
        'operations/enterprise-operations',
        'operations/responsibility-model',
      ],
    },

    section('Ship'),
    {
      type: 'category',
      label: 'Use Cases',
      link: {
        type: 'generated-index',
        slug: '/use-cases',
        title: 'Use Cases',
        description:
          'The same primitive — sign, then verify — applied to login, approvals, payouts, M2M, and autonomous agents.',
      },
      items: [
        'use-cases/passwordless-saas-login',
        'use-cases/step-up-authentication',
        'use-cases/admin-approval',
        'use-cases/payments-and-payouts',
        'use-cases/machine-to-machine',
        'use-cases/ai-agents-and-workflows',
        'use-cases/enterprise-use-cases',
      ],
    },
    {
      type: 'category',
      label: 'Product & Access',
      link: {
        type: 'generated-index',
        slug: '/product-and-access',
        title: 'Product & Access',
        description: 'Plans, the PTERI Wallet app, and how to get keys.',
      },
      items: ['product-and-access/pricing-plans', 'product-and-access/wallet-app'],
    },

    section('Help'),
    {
      type: 'category',
      label: 'Help & Support',
      link: {
        type: 'generated-index',
        slug: '/help',
        title: 'Help & Support',
        description:
          'Common questions, error messages you may hit, and where to check whether it is us or you.',
      },
      items: [
        'help/faqs',
        'help/developer-faqs-and-errors',
        'help/status-and-support',
        'help/verification-queue',
      ],
    },
  ],
};

export default sidebars;
